#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Sep 12 22:52:08 CEST 2024
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=BSL_v8.2.09.zip
