#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu May 07 01:52:32 PDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=Better MC - Medium
