# This is Carpet Mod's default configuration file
# Settings specified here will be used when a world doesn't have a config file, but they will be completely ignored once the world has one.
locked
defaultLoggers mobcaps,tps
lagFreeSpawning true
thickFungusGrowth random
renewableCoral true
betterBonemeal true
antiCheatDisabled true